import 'package:flutter/material.dart';

class Bird {
  final String id;
  final String name;
  final String emoji;
  final Color color;
  final String description;
  final String imagePath;

  const Bird({
    required this.id,
    required this.name,
    required this.emoji,
    required this.color,
    required this.description,
    required this.imagePath,
  });
}

const List<Bird> availableBirds = [
  Bird(
    id: 'blackbird',
    name: 'Blackbird',
    emoji: '🐦‍⬛',
    color: Colors.black87,
    description: 'Master of stealth.',
    imagePath: 'assets/images/birds/blackbird.png',
  ),
  Bird(
    id: 'blue_tit',
    name: 'Blue Tit',
    emoji: '🐦',
    color: Colors.blueAccent,
    description: 'A colorful garden visitor.',
    imagePath: 'assets/images/birds/blue_tit.png',
  ),
  Bird(
    id: 'bullfinch',
    name: 'Bullfinch',
    emoji: '🐦',
    color: Colors.pink,
    description: 'A plump and bright finch.',
    imagePath: 'assets/images/birds/bullfinch.png',
  ),
  Bird(
    id: 'chaffinch',
    name: 'Chaffinch',
    emoji: '🐦',
    color: Colors.brown,
    description: 'Known for its loud song.',
    imagePath: 'assets/images/birds/chaffinch.png',
  ),
  Bird(
    id: 'crow',
    name: 'Crow',
    emoji: '🐦‍⬛',
    color: Colors.black,
    description: 'Highly intelligent and resourceful.',
    imagePath: 'assets/images/birds/crow.png',
  ),
  Bird(
    id: 'goldfinch',
    name: 'Goldfinch',
    emoji: '🐦',
    color: Colors.redAccent,
    description: 'Loves thistle seeds.',
    imagePath: 'assets/images/birds/goldfinch.png',
  ),
  Bird(
    id: 'great_tit',
    name: 'Great Tit',
    emoji: '🐦',
    color: Colors.green,
    description: 'The largest of the UK tits.',
    imagePath: 'assets/images/birds/great_tit.png',
  ),
  Bird(
    id: 'heron',
    name: 'Heron',
    emoji: '🦩',
    color: Colors.grey,
    description: 'A patient water-side hunter.',
    imagePath: 'assets/images/birds/heron.png',
  ),
  Bird(
    id: 'kingfisher',
    name: 'Kingfisher',
    emoji: '🐦',
    color: Colors.lightBlue,
    description: 'A brilliant flash of blue by the river.',
    imagePath: 'assets/images/birds/kingfisher.png',
  ),
  Bird(
    id: 'magpie',
    name: 'Magpie',
    emoji: '🐦',
    color: Colors.blueGrey,
    description: 'One for sorrow, two for mirth.',
    imagePath: 'assets/images/birds/magpie.png',
  ),
  Bird(
    id: 'puffin',
    name: 'Puffin',
    emoji: '🐧',
    color: Colors.orange,
    description: 'The clown of the sea.',
    imagePath: 'assets/images/birds/puffin.png',
  ),
  Bird(
    id: 'robin',
    name: 'Robin',
    emoji: '🐦',
    color: Colors.red,
    description: 'Fiercely territorial and friendly.',
    imagePath: 'assets/images/birds/robin.png',
  ),
  Bird(
    id: 'woodpecker',
    name: 'Woodpecker',
    emoji: '🐦',
    color: Colors.redAccent,
    description: 'Famous for drumming on trees.',
    imagePath: 'assets/images/birds/woodpecker.png',
  ),
  Bird(
    id: 'wren',
    name: 'Wren',
    emoji: '🐦',
    color: Colors.brown,
    description: 'Tiny size, huge voice.',
    imagePath: 'assets/images/birds/wren.png',
  ),
  Bird(
    id: 'barn_owl',
    name: 'Barn Owl',
    emoji: '🦉',
    color: Colors.brown,
    description: 'A pale, ghostly owl.',
    imagePath: 'assets/images/birds/barn_owl.png',
  ),
  Bird(
    id: 'buzzard',
    name: 'Buzzard',
    emoji: '🦅',
    color: Colors.brown,
    description: 'A large bird of prey soaring high.',
    imagePath: 'assets/images/birds/buzzard.png',
  ),
  Bird(
    id: 'goldcrest',
    name: 'Goldcrest',
    emoji: '🐦',
    color: Colors.amber,
    description: 'The UK\'s smallest bird.',
    imagePath: 'assets/images/birds/goldcrest.png',
  ),
  Bird(
    id: 'kestrel',
    name: 'Kestrel',
    emoji: '🦅',
    color: Colors.brown,
    description: 'Famed for hovering alongside roads.',
    imagePath: 'assets/images/birds/kestrel.png',
  ),
  Bird(
    id: 'mallard',
    name: 'Mallard',
    emoji: '🦆',
    color: Colors.green,
    description: 'The classic dabbling duck.',
    imagePath: 'assets/images/birds/mallard.png',
  ),
  Bird(
    id: 'red_kite',
    name: 'Red Kite',
    emoji: '🦅',
    color: Colors.redAccent,
    description: 'A graceful, fork-tailed bird of prey.',
    imagePath: 'assets/images/birds/red_kite.png',
  ),
  Bird(
    id: 'siskin',
    name: 'Siskin',
    emoji: '🐦',
    color: Colors.yellow,
    description: 'A small, lively yellow-green finch.',
    imagePath: 'assets/images/birds/siskin.png',
  ),
  Bird(
    id: 'jackdaw',
    name: 'Jackdaw',
    emoji: '🐦‍⬛',
    color: Colors.grey,
    description: 'A sociable, silver-headed crow.',
    imagePath: 'assets/images/birds/jackdaw.png',
  ),
  Bird(
    id: 'dunnock',
    name: 'Dunnock',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A quiet, unassuming bird of the undergrowth.',
    imagePath: 'assets/images/birds/dunnock.png',
  ),
  Bird(
    id: 'starling',
    name: 'Starling',
    emoji: '🐦‍⬛',
    color: Colors.deepPurple,
    description: 'Known for their mesmerizing murmurations.',
    imagePath: 'assets/images/birds/starling.png',
  ),
  Bird(
    id: 'song_thrush',
    name: 'Song Thrush',
    emoji: '🐦',
    color: Colors.brown,
    description: 'Famous for repeating its musical phrases.',
    imagePath: 'assets/images/birds/song_thrush.png',
  ),
  Bird(
    id: 'long_tailed_tit',
    name: 'Long-tailed Tit',
    emoji: '🐦',
    color: Colors.pinkAccent,
    description: 'A tiny, fluffy bird with a very long tail.',
    imagePath: 'assets/images/birds/long_tailed_tit.png',
  ),
  Bird(
    id: 'moorhen',
    name: 'Moorhen',
    emoji: '🦆',
    color: Colors.black87,
    description: 'A waterbird with a distinctive red and yellow bill.',
    imagePath: 'assets/images/birds/moorhen.png',
  ),
  Bird(
    id: 'coal_tit',
    name: 'Coal Tit',
    emoji: '🐦',
    color: Colors.grey,
    description: 'A small tit with a white patch on the back of its neck.',
    imagePath: 'assets/images/birds/coal_tit.png',
  ),
  Bird(
    id: 'house_sparrow',
    name: 'House Sparrow',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A noisy and gregarious familiar friend.',
    imagePath: 'assets/images/birds/house_sparrow.png',
  ),
  Bird(
    id: 'redwing',
    name: 'Redwing',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A winter visitor with a bright red flank.',
    imagePath: 'assets/images/birds/redwing.png',
  ),
  Bird(
    id: 'curlew',
    name: 'Curlew',
    emoji: '🦩',
    color: Colors.brown,
    description: 'Our largest wading bird with a long, down-curved bill.',
    imagePath: 'assets/images/birds/curlew.png',
  ),
];
