import 'package:flutter/material.dart';

class Bird {
  final String id;
  final String name;
  final String emoji;
  final Color color;
  final String description;
  final String imagePath;
  final bool hasEvolution;

  const Bird({
    required this.id,
    required this.name,
    required this.emoji,
    required this.color,
    required this.description,
    required this.imagePath,
    this.hasEvolution = false,
  });

  String getEvolvedImagePath(int evolutionStage) {
    if (!hasEvolution) return imagePath;
    int stage = evolutionStage.clamp(1, 5);
    return 'assets/bird_evolution/${id}_$stage.webp';
  }
}

const List<Bird> availableBirds = [
  Bird(
    id: 'blackbird',
    name: 'Blackbird',
    emoji: '🐦‍⬛',
    color: Colors.black87,
    description: 'Master of stealth.',
    imagePath: 'assets/bird_icons/blackbird.webp',
    hasEvolution: true,
  ),
  Bird(
    id: 'blue_tit',
    name: 'Blue Tit',
    emoji: '🐦',
    color: Colors.blueAccent,
    description: 'A colorful garden visitor.',
    imagePath: 'assets/bird_icons/blue_tit.webp',
    hasEvolution: true,
  ),
  Bird(
    id: 'bullfinch',
    name: 'Bullfinch',
    emoji: '🐦',
    color: Colors.pink,
    description: 'A plump and bright finch.',
    imagePath: 'assets/bird_icons/bullfinch.webp',
  ),
  Bird(
    id: 'chaffinch',
    name: 'Chaffinch',
    emoji: '🐦',
    color: Colors.brown,
    description: 'Known for its loud song.',
    imagePath: 'assets/bird_icons/chaffinch.webp',
  ),
  Bird(
    id: 'crow',
    name: 'Crow',
    emoji: '🐦‍⬛',
    color: Colors.black,
    description: 'Highly intelligent and resourceful.',
    imagePath: 'assets/bird_icons/crow.webp',
  ),
  Bird(
    id: 'goldfinch',
    name: 'Goldfinch',
    emoji: '🐦',
    color: Colors.redAccent,
    description: 'Loves thistle seeds.',
    imagePath: 'assets/bird_icons/goldfinch.webp',
  ),
  Bird(
    id: 'great_tit',
    name: 'Great Tit',
    emoji: '🐦',
    color: Colors.green,
    description: 'The largest of the UK tits.',
    imagePath: 'assets/bird_icons/great_tit.webp',
  ),
  Bird(
    id: 'heron',
    name: 'Heron',
    emoji: '🦩',
    color: Colors.grey,
    description: 'A patient water-side hunter.',
    imagePath: 'assets/bird_icons/heron.webp',
  ),
  Bird(
    id: 'kingfisher',
    name: 'Kingfisher',
    emoji: '🐦',
    color: Colors.lightBlue,
    description: 'A brilliant flash of blue by the river.',
    imagePath: 'assets/bird_icons/kingfisher.webp',
  ),
  Bird(
    id: 'magpie',
    name: 'Magpie',
    emoji: '🐦',
    color: Colors.blueGrey,
    description: 'One for sorrow, two for mirth.',
    imagePath: 'assets/bird_icons/magpie.webp',
  ),
  Bird(
    id: 'puffin',
    name: 'Puffin',
    emoji: '🐧',
    color: Colors.orange,
    description: 'The clown of the sea.',
    imagePath: 'assets/bird_icons/puffin.webp',
  ),
  Bird(
    id: 'robin',
    name: 'Robin',
    emoji: '🐦',
    color: Colors.red,
    description: 'Fiercely territorial and friendly.',
    imagePath: 'assets/bird_icons/robin.webp',
    hasEvolution: true,
  ),
  Bird(
    id: 'woodpecker',
    name: 'Woodpecker',
    emoji: '🐦',
    color: Colors.redAccent,
    description: 'Famous for drumming on trees.',
    imagePath: 'assets/bird_icons/woodpecker.webp',
  ),
  Bird(
    id: 'wren',
    name: 'Wren',
    emoji: '🐦',
    color: Colors.brown,
    description: 'Tiny size, huge voice.',
    imagePath: 'assets/bird_icons/wren.webp',
  ),
  Bird(
    id: 'wood_pigeon',
    name: 'Wood Pigeon',
    emoji: '🕊️',
    color: Colors.grey,
    description: 'A massive, familiar pigeon of woods and gardens.',
    imagePath: 'assets/bird_evolution/wood_pigeon_1.webp',
    hasEvolution: true,
  ),
  Bird(
    id: 'barn_owl',
    name: 'Barn Owl',
    emoji: '🦉',
    color: Colors.brown,
    description: 'A pale, ghostly owl.',
    imagePath: 'assets/bird_icons/barn_owl.webp',
    hasEvolution: true,
  ),
  Bird(
    id: 'buzzard',
    name: 'Buzzard',
    emoji: '🦅',
    color: Colors.brown,
    description: 'A large bird of prey soaring high.',
    imagePath: 'assets/bird_icons/buzzard.webp',
  ),
  Bird(
    id: 'goldcrest',
    name: 'Goldcrest',
    emoji: '🐦',
    color: Colors.amber,
    description: 'The UK\'s smallest bird.',
    imagePath: 'assets/bird_icons/goldcrest.webp',
  ),
  Bird(
    id: 'kestrel',
    name: 'Kestrel',
    emoji: '🦅',
    color: Colors.brown,
    description: 'Famed for hovering alongside roads.',
    imagePath: 'assets/bird_icons/kestrel.webp',
  ),
  Bird(
    id: 'mallard',
    name: 'Mallard',
    emoji: '🦆',
    color: Colors.green,
    description: 'The classic dabbling duck.',
    imagePath: 'assets/bird_icons/mallard.webp',
    hasEvolution: true,
  ),
  Bird(
    id: 'red_kite',
    name: 'Red Kite',
    emoji: '🦅',
    color: Colors.redAccent,
    description: 'A graceful, fork-tailed bird of prey.',
    imagePath: 'assets/bird_icons/red_kite.webp',
  ),
  Bird(
    id: 'siskin',
    name: 'Siskin',
    emoji: '🐦',
    color: Colors.yellow,
    description: 'A small, lively yellow-green finch.',
    imagePath: 'assets/bird_icons/siskin.webp',
  ),
  Bird(
    id: 'jackdaw',
    name: 'Jackdaw',
    emoji: '🐦‍⬛',
    color: Colors.grey,
    description: 'A sociable, silver-headed crow.',
    imagePath: 'assets/bird_icons/jackdaw.webp',
  ),
  Bird(
    id: 'dunnock',
    name: 'Dunnock',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A quiet, unassuming bird of the undergrowth.',
    imagePath: 'assets/bird_icons/dunnock.webp',
  ),
  Bird(
    id: 'starling',
    name: 'Starling',
    emoji: '🐦‍⬛',
    color: Colors.deepPurple,
    description: 'Known for their mesmerizing murmurations.',
    imagePath: 'assets/bird_icons/starling.webp',
  ),
  Bird(
    id: 'song_thrush',
    name: 'Song Thrush',
    emoji: '🐦',
    color: Colors.brown,
    description: 'Famous for repeating its musical phrases.',
    imagePath: 'assets/bird_icons/song_thrush.webp',
  ),
  Bird(
    id: 'long_tailed_tit',
    name: 'Long-tailed Tit',
    emoji: '🐦',
    color: Colors.pinkAccent,
    description: 'A tiny, fluffy bird with a very long tail.',
    imagePath: 'assets/bird_icons/long_tailed_tit.webp',
  ),
  Bird(
    id: 'moorhen',
    name: 'Moorhen',
    emoji: '🦆',
    color: Colors.black87,
    description: 'A waterbird with a distinctive red and yellow bill.',
    imagePath: 'assets/bird_icons/moorhen.webp',
  ),
  Bird(
    id: 'coal_tit',
    name: 'Coal Tit',
    emoji: '🐦',
    color: Colors.grey,
    description: 'A small tit with a white patch on the back of its neck.',
    imagePath: 'assets/bird_icons/coal_tit.webp',
  ),
  Bird(
    id: 'house_sparrow',
    name: 'House Sparrow',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A noisy and gregarious familiar friend.',
    imagePath: 'assets/bird_icons/house_sparrow.webp',
  ),
  Bird(
    id: 'redwing',
    name: 'Redwing',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A winter visitor with a bright red flank.',
    imagePath: 'assets/bird_icons/redwing.webp',
  ),
  Bird(
    id: 'curlew',
    name: 'Curlew',
    emoji: '🦩',
    color: Colors.brown,
    description: 'Our largest wading bird with a long, down-curved bill.',
    imagePath: 'assets/bird_icons/curlew.webp',
  ),
  Bird(
    id: 'shelduck',
    name: 'Shelduck',
    emoji: '🦆',
    color: Colors.orange,
    description: 'A large, colorful waterfowl resembling a small goose.',
    imagePath: 'assets/bird_icons/shelduck.webp',
  ),
  Bird(
    id: 'wigeon',
    name: 'Wigeon',
    emoji: '🦆',
    color: Colors.brown,
    description: 'A medium-sized duck with a whistling call.',
    imagePath: 'assets/bird_icons/wigeon.webp',
  ),
  Bird(
    id: 'pintail',
    name: 'Pintail',
    emoji: '🦆',
    color: Colors.brown,
    description: 'An elegant duck with a long, pointed tail.',
    imagePath: 'assets/bird_icons/pintail.webp',
  ),
  Bird(
    id: 'rook',
    name: 'Rook',
    emoji: '🐦‍⬛',
    color: Colors.black,
    description: 'A sociable member of the crow family with a bare face.',
    imagePath: 'assets/bird_icons/rook.webp',
  ),
  Bird(
    id: 'stonechat',
    name: 'Stonechat',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A heathland bird with a call like striking stones together.',
    imagePath: 'assets/bird_icons/stonechat.webp',
  ),
  Bird(
    id: 'dipper',
    name: 'Dipper',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A plump bird that bobs, dives, and walks underwater.',
    imagePath: 'assets/bird_icons/dipper.webp',
  ),
  Bird(
    id: 'waxwing',
    name: 'Waxwing',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A striking winter visitor with a prominent crest.',
    imagePath: 'assets/bird_icons/waxwing.webp',
  ),
  Bird(
    id: 'willow_tit',
    name: 'Willow Tit',
    emoji: '🐦',
    color: Colors.grey,
    description: 'A secretive tit that excavates its own nest hole.',
    imagePath: 'assets/bird_icons/willow_tit.webp',
  ),
  Bird(
    id: 'nuthatch',
    name: 'Nuthatch',
    emoji: '🐦',
    color: Colors.blueGrey,
    description: 'The only UK bird that can climb down tree trunks headfirst.',
    imagePath: 'assets/bird_icons/nuthatch.webp',
  ),
  Bird(
    id: 'chiffchaff',
    name: 'Chiffchaff',
    emoji: '🐦',
    color: Colors.lightGreen,
    description: 'A small warbler named after its repetitive song.',
    imagePath: 'assets/bird_icons/chiffchaff.webp',
  ),
  Bird(
    id: 'skylark',
    name: 'Skylark',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A streaky brown bird famous for its complex song flight.',
    imagePath: 'assets/bird_icons/skylark.webp',
  ),
  Bird(
    id: 'yellowhammer',
    name: 'Yellowhammer',
    emoji: '🐦',
    color: Colors.yellow,
    description: 'A bright yellow bird of the hedgerows.',
    imagePath: 'assets/bird_icons/yellowhammer.webp',
  ),
  Bird(
    id: 'reed_bunting',
    name: 'Reed Bunting',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A sparrow-like bird found in wetlands and farmland.',
    imagePath: 'assets/bird_icons/reed_bunting.webp',
  ),
  Bird(
    id: 'brambling',
    name: 'Brambling',
    emoji: '🐦',
    color: Colors.orange,
    description: 'A migratory finch that visits in the winter.',
    imagePath: 'assets/bird_icons/brambling.webp',
  ),
  Bird(
    id: 'linnet',
    name: 'Linnet',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A small, slim finch with a melodious song.',
    imagePath: 'assets/bird_icons/linnet.webp',
  ),
  Bird(
    id: 'loon',
    name: 'Loon',
    emoji: '🦆',
    color: Colors.black87,
    description: 'A striking diving bird with a haunting call.',
    imagePath: 'assets/bird_icons/loon.webp',
  ),
  Bird(
    id: 'razorbill',
    name: 'Razorbill',
    emoji: '🐧',
    color: Colors.black,
    description: 'A robust seabird with a distinctive, thick bill.',
    imagePath: 'assets/bird_icons/razorbill.webp',
  ),
  Bird(
    id: 'fulmar',
    name: 'Fulmar',
    emoji: '🕊️',
    color: Colors.grey,
    description: 'A gull-like seabird that glides stiff-winged over waves.',
    imagePath: 'assets/bird_icons/fulmar.webp',
  ),
  Bird(
    id: 'avocet',
    name: 'Avocet',
    emoji: '🦩',
    color: Colors.black,
    description: 'An elegant wader with a unique upward-curving bill.',
    imagePath: 'assets/bird_icons/avocet.webp',
  ),
  Bird(
    id: 'shag',
    name: 'Shag',
    emoji: '🦆',
    color: Colors.black87,
    description: 'A coastal diving bird with a steep forehead and crest.',
    imagePath: 'assets/bird_icons/shag.webp',
  ),
  Bird(
    id: 'eider',
    name: 'Eider',
    emoji: '🦆',
    color: Colors.brown,
    description: 'A heavy sea duck famous for its soft down.',
    imagePath: 'assets/bird_icons/eider.webp',
  ),
  Bird(
    id: 'lapwing',
    name: 'Lapwing',
    emoji: '🐦',
    color: Colors.green,
    description: 'A familiar wader with a prominent crest and peewit call.',
    imagePath: 'assets/bird_icons/lapwing.webp',
  ),
  Bird(
    id: 'redshank',
    name: 'Redshank',
    emoji: '🦩',
    color: Colors.brown,
    description: 'A noisy wader with bright orange-red legs.',
    imagePath: 'assets/bird_icons/redshank.webp',
  ),
  Bird(
    id: 'snipe',
    name: 'Snipe',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A cryptic wader with an extraordinarily long, straight bill.',
    imagePath: 'assets/bird_icons/snipe.webp',
  ),
  Bird(
    id: 'dunlin',
    name: 'Dunlin',
    emoji: '🐦',
    color: Colors.brown,
    description: 'Our most common small wader on estuaries in winter.',
    imagePath: 'assets/bird_icons/dunlin.webp',
  ),
  Bird(
    id: 'goshawk',
    name: 'Goshawk',
    emoji: '🦅',
    color: Colors.brown,
    description: 'A powerful, fierce forest hawk.',
    imagePath: 'assets/bird_icons/goshawk.webp',
  ),
  Bird(
    id: 'jay',
    name: 'Jay',
    emoji: '🐦',
    color: Colors.pinkAccent,
    description:
        'A colorful member of the crow family, known for burying acorns.',
    imagePath: 'assets/bird_icons/jay.webp',
  ),
  Bird(
    id: 'blackcap',
    name: 'Blackcap',
    emoji: '🐦',
    color: Colors.grey,
    description: 'A grey warbler with a distinctive black (or brown) cap.',
    imagePath: 'assets/bird_icons/blackcap.webp',
  ),
  Bird(
    id: 'pheasant',
    name: 'Pheasant',
    emoji: '🦚',
    color: Colors.orange,
    description: 'A large, colorful gamebird with a long tail.',
    imagePath: 'assets/bird_icons/pheasant.webp',
  ),
  Bird(
    id: 'coot',
    name: 'Coot',
    emoji: '🦆',
    color: Colors.black,
    description:
        'An all-black waterbird with a distinctive white beak and frontal shield.',
    imagePath: 'assets/bird_icons/coot.webp',
  ),
  Bird(
    id: 'turnstone',
    name: 'Turnstone',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A robust shorebird known for flipping stones to find food.',
    imagePath: 'assets/bird_icons/turnstone.webp',
  ),
  Bird(
    id: 'sandpiper',
    name: 'Sandpiper',
    emoji: '🐦',
    color: Colors.brown,
    description: 'A small, active wader usually seen running along the shore.',
    imagePath: 'assets/bird_icons/sandpiper.webp',
  ),
  Bird(
    id: 'oystercatcher',
    name: 'Oystercatcher',
    emoji: '🦩',
    color: Colors.black87,
    description:
        'A noisy wader with black-and-white plumage and a long orange bill.',
    imagePath: 'assets/bird_icons/oystercatcher.webp',
  ),
  Bird(
    id: 'gull',
    name: 'Gull',
    emoji: '🕊️',
    color: Colors.grey,
    description:
        'A familiar, grey-and-white seabird often seen scavenging near the coast.',
    imagePath: 'assets/bird_icons/gull.webp',
  ),
  Bird(
    id: 'teal',
    name: 'Teal',
    emoji: '🦆',
    color: Colors.brown,
    description:
        'A small dabbling duck, males having a distinctive green eye-patch.',
    imagePath: 'assets/bird_icons/teal.webp',
  ),
];
